syntax enable           " enable syntax highlighting
set expandtab           " tabs are spaces
set ts=2                " tabstop is 2 (default 8)
set sw=2                " shiftwidth is 2 (default 8)
set modeline            " follow modes set in a file (possible security issue)
set modelines=5         " sometimes need this for mac
set ignorecase          " ignore case in search
set smartcase           " case-insensitive search if all lowercase

" use Markdown syntax for .md files
augroup markdown        
    " remove previous autocmds
    autocmd!
    " set every new or read *.md buffer to use the markdown filetype 
    autocmd BufRead,BufNew *.md set filetype=markdown
augroup END

" signature for documents
:inoremap <F2> ---calvin <C-R>=strftime("%Y-%m-%d")<CR>
" having the date is useful
:inoremap <F3> <C-R>=strftime("%Y-%m-%d")<CR>
" call common compiling utilities
:noremap <F7> :!pdflatex %<CR>
:noremap <F8> :!make<CR>

autocmd BufWinLeave *.* mkview
autocmd BufWinEnter *.* silent loadview 

function! TwiddleCase(str)
  if a:str ==# toupper(a:str)
    let result = tolower(a:str)
  elseif a:str ==# tolower(a:str)
    let result = substitute(a:str,'\(\<\w\+\>\)', '\u\1', 'g')
  else
    let result = toupper(a:str)
  endif
  return result
endfunction
vnoremap ~ y:call setreg('', TwiddleCase(@"), getregtype(''))<CR>gv""Pgv
